import { BenefitCard } from "@/components/benefits";
import { Carousel } from "@/components/Carousel";
import { CaseStudy } from "@/components/caseStudy/CaseStudy";
import { Heading } from "@/components/Heading";
import { HeroSection } from "@/components/HeroSection";
import { Polygon } from "@/components/ui/polygon";
import { benefitCardData } from "@/data/benefits";

export const metadata = {
  title: "About | Chalti Firti Dukan",
  description: "Generated by create next app",
};

export default function About() {
  const slides = ["/images/store_view.jpg"];
  return (
    <>
      <section className="bg-primary pt-4">
        <Heading title={"Humari Pehchan"} />
        <HeroSection />
      </section>
      <Polygon className={"bg-white"} />
      <section>
        <Heading title={"Store Inside View"} primary />
        <div className="px-10">
          <Carousel slides={slides} />
        </div>
      </section>
      <Polygon reverse className={"bg-white"} />
      <section className="bg-primary py-4">
        <Heading title={"Benefits"} />
        <div className="mx-auto grid max-w-screen-lg grid-cols-3 gap-4 px-4 pt-3 max-md:grid-cols-2 max-sm:grid-cols-1">
          {benefitCardData.map(
            ({ title, description, image, backgroundColor }) => (
              <BenefitCard
                key={title}
                title={title}
                description={description}
                image={image}
                background={backgroundColor}
              />
            )
          )}
        </div>
      </section>
      <Polygon />
     <CaseStudy />
     <Heading title={"costing plan"} primary />
    </>
  );
}
